### ISSUE TITLE
Decryption with gpgme-sharp

### ISSUE THREAD

**Issue by Net-Head** [gpgme-sharp/gpgme-sharp#16]
Hello

I’m using the gpgme-sharp dll to test encryption and decryption of text files.
The encryption works perfectly and creates the .gpg encrypted file.

When I try to decrypt the .gpg file, I get the error below which looks like an unspecified error.
When I use Kleopatra to decrypt my created .gpg file, it works fine.

Could you please be so kind as to assist me or point me in the right direction?
I’m attaching my sample .txt file as well as a screengrab of error point in VS.

Thanks in advance and best regards
Stefan
[SourceFile.txt](https://github.com/gpgme-sharp/gpgme-sharp/files/8772620/SourceFile.txt)

Excerpt from my error 
![gpgme_error](https://user-images.githubusercontent.com/106243171/170304183-553286df-c667-4693-ad19-a95395af2a17.png)
log below:

Libgpgme.GeneralErrorException
  HResult=0x80131500
  Message=#GPG_ERR_CANCELED: $Operation cancelled
  Source=gpgme-sharp
  StackTrace:
   at Libgpgme.Context.Decrypt(GpgmeData cipher, GpgmeData plain) in D:\XXXXXXXX\AAA Class Libraries\gpgme-sharp\gpgme-sharp\Context.cs:line 545
   at Libgpgme.StefEncryptDecrypt.Main(String Passphrase, String SourceFileName, String PreEncriptFileName, String CipherFileName, String DecryptedFileName) in D:\XXXXXXXX\AAA Class Libraries\gpgme-sharp\gpgme-sharp\StefDecrypt.cs:line 132
   at Libgpgme.FromVBDecryptCall.Main(String Passphrase, String SourceFileName, String PreEncriptFileName, String CipherFileName, String DecryptedFileName) in D:\XXXXXXXX\AAA Class Libraries\gpgme-sharp\gpgme-sharp\VBDecryptCall.cs:line 14
   at TestApp_Decryption.Form1.Button1_Click(Object sender, EventArgs e) in D:\ XXXXXXXX \TestApp -

**Comment by Daniel15** [comment]
Hmm, unfortunately I'm not sure about this one. You might need to ask on the gnupg-devel mailing list: https://lists.gnupg.org/mailman/listinfo/gnupg-devel.

Otherwise, can you please post some example code to a GitHub repo so I can clone it and replicate the error?
